<a href="https://colab.research.google.com/github/Suman-Poola/Random-Forrest-s-p500/blob/main/Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from fastai import *
import pandas as pd
from google.colab import userdata
import os
import zipfile
import numpy as np

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

import kaggle

In [24]:
dataset_id = 'darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily'
path = 'ticker_list'
kaggle.api.dataset_download_cli(dataset_id, path = str(path), unzip=True, force=True)

Dataset URL: https://www.kaggle.com/datasets/darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily
License(s): CC0-1.0
Downloading s-and-p-500-stocks-25-years-of-data-updated-daily.zip to ticker_list

100%|██████████| 100M/100M [00:00<00:00, 167MB/s]

In [25]:
!ls {path}

sp500_companies.csv  sp500_stocks.csv

In [26]:
tk = pd.read_csv('ticker_list/sp500_companies.csv')
tk.head()

,symbol,company,sector,sub_industry,headquarters,date_added,founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1989

In [27]:
import numpy as np
tickers = tk['symbol'].tolist()
tickers[0:25]

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE']

In [28]:
len(tickers)

503

In [29]:
tickers[499:503]

['YUM', 'ZBRA', 'ZBH', 'ZTS']

In [30]:
import yfinance as yf
df = yf.download(tickers, period="36mo")
df.head()

/tmp/ipykernel_6127/2136594173.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, period="36mo")
[*********************100%***********************]  503 of 503 completed

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2023-09-05  116.049263  187.168533  131.721832  142.289993  94.771317
2023-09-06  115.277092  180.469147  131.280060  141.770004  95.410118
2023-09-07  113.635025  175.190536  134.255295  143.270004  94.574028
2023-09-08  111.416275  175.802231  134.354446  145.820007  94.630402
2023-09-11  110.546364  176.966522  134.372482  147.330002  96.246254

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2023-09-05  72.135162  308.810638  564.880005  173.242661  71.351151  ...
2023-09-06  72.686684  308.943146  561.940002  173.853409  70.066689  ...
2023-09-07  74.046471  310.742126  560.460022  170.303406  71.034561  ...
2023-09-08  73.466423  308.157349  560.359985  169.358688  71.287842  ...
2023-09-11  74.930809  308.536102  564.500000  169.530441  71.224525  ...

Price          Volume                                                       \
Ticker             WY     WYNN      XEL         XOM        XYL         XYZ
Date
2023-09-05  4133700.0  3084700  4170400  18304000.0  2679700.0   5987000.0
2023-09-06  3342700.0  1896200  3815400  13325500.0  1514400.0  10491600.0
2023-09-07  3199500.0  3111300  3554900  13248500.0  1807100.0   9075800.0
2023-09-08  3303400.0  1466700  3627800  14283200.0  1690800.0  20691100.0
2023-09-11  2227200.0  1068600  5586300  14383600.0  1617400.0  10420000.0

Price
Ticker          YUM      ZBH    ZBRA        ZTS
Date
2023-09-05  1435900  1645000  417300  1673000.0
2023-09-06  1710200  3625200  327200  1356800.0
2023-09-07  1396800  1816400  498100  1159600.0
2023-09-08   728900  1104500  435000  1562200.0
2023-09-11   981700  1285900  358400  1069100.0

[5 rows x 2515 columns]

In [31]:
df.head()

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2023-09-05  116.049263  187.168533  131.721832  142.289993  94.771317
2023-09-06  115.277092  180.469147  131.280060  141.770004  95.410118
2023-09-07  113.635025  175.190536  134.255295  143.270004  94.574028
2023-09-08  111.416275  175.802231  134.354446  145.820007  94.630402
2023-09-11  110.546364  176.966522  134.372482  147.330002  96.246254

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2023-09-05  72.135162  308.810638  564.880005  173.242661  71.351151  ...
2023-09-06  72.686684  308.943146  561.940002  173.853409  70.066689  ...
2023-09-07  74.046471  310.742126  560.460022  170.303406  71.034561  ...
2023-09-08  73.466423  308.157349  560.359985  169.358688  71.287842  ...
2023-09-11  74.930809  308.536102  564.500000  169.530441  71.224525  ...

Price          Volume                                                       \
Ticker             WY     WYNN      XEL         XOM        XYL         XYZ
Date
2023-09-05  4133700.0  3084700  4170400  18304000.0  2679700.0   5987000.0
2023-09-06  3342700.0  1896200  3815400  13325500.0  1514400.0  10491600.0
2023-09-07  3199500.0  3111300  3554900  13248500.0  1807100.0   9075800.0
2023-09-08  3303400.0  1466700  3627800  14283200.0  1690800.0  20691100.0
2023-09-11  2227200.0  1068600  5586300  14383600.0  1617400.0  10420000.0

Price
Ticker          YUM      ZBH    ZBRA        ZTS
Date
2023-09-05  1435900  1645000  417300  1673000.0
2023-09-06  1710200  3625200  327200  1356800.0
2023-09-07  1396800  1816400  498100  1159600.0
2023-09-08   728900  1104500  435000  1562200.0
2023-09-11   981700  1285900  358400  1069100.0

[5 rows x 2515 columns]

In [32]:
closes = df["Close"]
returns = closes.pct_change() *100

volumes = df['Volume']

cs = closes.stack().rename("Close")
rs = returns.stack().rename("Returns")
vs = volumes.stack().rename("Volume")
fdf = pd.concat([cs,rs,vs], axis = 1).reset_index()

fdf.columns = ['date', 'ticker', 'close', 'return', 'volume']
fdf = fdf.dropna(subset=['return'])

fdf.head(25)

/tmp/ipykernel_6127/4234654860.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = closes.pct_change() *100

          date ticker       close    return      volume
495 2023-09-06      A  115.277092 -0.665382   1668900.0
496 2023-09-06   AAPL  180.469147 -3.579334  81755800.0
497 2023-09-06   ABBV  131.280060 -0.335383   5304300.0
498 2023-09-06   ABNB  141.770004 -0.365443   7114400.0
499 2023-09-06    ABT   95.410118  0.674045   5094400.0
500 2023-09-06   ACGL   72.686684  0.764567    922800.0
501 2023-09-06    ACN  308.943146  0.042909   1247900.0
502 2023-09-06   ADBE  561.940002 -0.520465   2299900.0
503 2023-09-06    ADI  173.853409  0.352539   3382500.0
504 2023-09-06    ADM   70.066689 -1.800198   3563900.0
505 2023-09-06    ADP  233.969437 -0.711892   1311000.0
506 2023-09-06   ADSK  222.199997  1.248515   1709700.0
507 2023-09-06    AEE   70.799110  0.504647   1205900.0
508 2023-09-06    AEP   68.546913  0.500007   2752300.0
509 2023-09-06    AES   15.046952 -0.057332  10449000.0
510 2023-09-06    AFL   69.647827  0.040427   2240900.0
511 2023-09-06    AIG   55.399822  1.006818   2787400.0
512 2023-09-06    AIZ  131.791885 -0.245819    336100.0
513 2023-09-06    AJG  221.854004  0.414471    519100.0
514 2023-09-06   AKAM  103.800003 -0.717360   1197800.0
515 2023-09-06    ALB  181.296844 -5.463141   2544100.0
516 2023-09-06   ALGN  369.700012  0.290266    618500.0
517 2023-09-06    ALL  101.951500  0.662196   1360300.0
518 2023-09-06   ALLE  104.403679 -2.402348   1301100.0
519 2023-09-06   AMAT  149.630844 -0.279924   3109600.0

fdf.sort_values(by=['ticker', 'date'], inplace=True)
fdf.head(25)

In [33]:
fdf.sort_values(['ticker', 'date'], inplace=True)
fdf.head(25)

            date ticker       close    return     volume
495   2023-09-06      A  115.277092 -0.665382  1668900.0
990   2023-09-07      A  113.635025 -1.424452  1317000.0
1485  2023-09-08      A  111.416275 -1.952523  1789800.0
1980  2023-09-11      A  110.546364 -0.780776  2046900.0
2475  2023-09-12      A  110.233589 -0.282935  2035000.0
2970  2023-09-13      A  110.868919  0.576349  2520500.0
3465  2023-09-14      A  112.286179  1.278320  1815800.0
3960  2023-09-15      A  113.292931  0.896595  6889600.0
4455  2023-09-18      A  110.145630 -2.778020  1818000.0
4950  2023-09-19      A  109.774200 -0.337217  2222400.0
5445  2023-09-20      A  109.930603  0.142477  1744900.0
5940  2023-09-21      A  107.252472 -2.436202  1327900.0
6435  2023-09-22      A  108.894524  1.531015  2050500.0
6930  2023-09-25      A  109.412560  0.475723   987400.0
7425  2023-09-26      A  108.229881 -1.080935  1399800.0
7920  2023-09-27      A  108.005074 -0.207713  2268300.0
8415  2023-09-28      A  109.471199  1.357460  1959900.0
8910  2023-09-29      A  109.295273 -0.160705  1830100.0
9405  2023-10-02      A  108.614601 -0.622782  1569000.0
9900  2023-10-03      A  107.987778 -0.577108  1543400.0
10395 2023-10-04      A  109.368736  1.278810  1541700.0
10891 2023-10-05      A  108.075928 -1.182064  1295700.0
11387 2023-10-06      A  108.359947  0.262796  1796100.0
11883 2023-10-09      A  108.986748  0.578443  1320300.0
12379 2023-10-10      A  110.955338  1.806265  2183000.0

In [34]:
df=fdf

In [35]:
len(df)

375035

In [36]:
df['Lag 1'] = df['close'].shift(1)
df['Lag 2'] = df['close'].shift(2)
df['Lag 3'] = df['close'].shift(3)
df['Lag 5'] = df['close'].shift(5)
df.head(200)

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5
495,2023-09-06,A,115.277092,-0.665382,1668900.0,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635025,-1.424452,1317000.0,115.277092,NaN,NaN,NaN
1485,2023-09-08,A,111.416275,-1.952523,1789800.0,113.635025,115.277092,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780776,2046900.0,111.416275,113.635025,115.277092,NaN
2475,2023-09-12,A,110.233589,-0.282935,2035000.0,110.546364,111.416275,113.635025,NaN
...,...,...,...,...,...,...,...,...,...
97365,2024-06-14,A,127.596100,-0.551430,2163300.0,128.303604,130.848679,129.816864,130.671783
97864,2024-06-17,A,129.541748,1.524849,2090500.0,127.596100,128.303604,130.848679,130.720917
98363,2024-06-18,A,132.558441,2.328742,3453000.0,129.541748,127.596100,128.303604,129.816864
98862,2024-06-20,A,130.426117,-1.608592,2887400.0,132.558441,129.541748,127.596100,130.848679
99361,2024-06-21,A,130.937103,0.391782,4449700.0,130.426117,132.558441,129.541748,128.303604

In [37]:
df['Lag 1'] = df.groupby('ticker')['close'].shift(1)
df['Lag 2'] = df.groupby('ticker')['close'].shift(2)
df['Lag 3'] = df.groupby('ticker')['close'].shift(3)
df['Lag 5'] = df.groupby('ticker')['close'].shift(5)
df.head(25)

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5
495,2023-09-06,A,115.277092,-0.665382,1668900.0,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635025,-1.424452,1317000.0,115.277092,NaN,NaN,NaN
1485,2023-09-08,A,111.416275,-1.952523,1789800.0,113.635025,115.277092,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780776,2046900.0,111.416275,113.635025,115.277092,NaN
2475,2023-09-12,A,110.233589,-0.282935,2035000.0,110.546364,111.416275,113.635025,NaN
2970,2023-09-13,A,110.868919,0.576349,2520500.0,110.233589,110.546364,111.416275,115.277092
3465,2023-09-14,A,112.286179,1.278320,1815800.0,110.868919,110.233589,110.546364,113.635025
3960,2023-09-15,A,113.292931,0.896595,6889600.0,112.286179,110.868919,110.233589,111.416275
4455,2023-09-18,A,110.145630,-2.778020,1818000.0,113.292931,112.286179,110.868919,110.546364
4950,2023-09-19,A,109.774200,-0.337217,2222400.0,110.145630,113.292931,112.286179,110.233589
5445,2023-09-20,A,109.930603,0.142477,1744900.0,109.774200,110.145630,113.292931,110.868919
5940,2023-09-21,A,107.252472,-2.436202,1327900.0,109.930603,109.774200,110.145630,112.286179
6435,2023-09-22,A,108.894524,1.531015,2050500.0,107.252472,109.930603,109.774200,113.292931
6930,2023-09-25,A,109.412560,0.475723,987400.0,108.894524,107.252472,109.930603,110.145630
7425,2023-09-26,A,108.229881,-1.080935,1399800.0,109.412560,108.894524,107.252472,109.774200
7920,2023-09-27,A,108.005074,-0.207713,2268300.0,108.229881,109.412560,108.894524,109.930603
8415,2023-09-28,A,109.471199,1.357460,1959900.0,108.005074,108.229881,109.412560,107.252472
8910,2023-09-29,A,109.295273,-0.160705,1830100.0,109.471199,108.005074,108.229881,108.894524
9405,2023-10-02,A,108.614601,-0.622782,1569000.0,109.295273,109.471199,108.005074,109.412560
9900,2023-10-03,A,107.987778,-0.577108,1543400.0,108.614601,109.295273,109.471199,108.229881
10395,2023-10-04,A,109.368736,1.278810,1541700.0,107.987778,108.614601,109.295273,108.005074
10891,2023-10-05,A,108.075928,-1.182064,1295700.0,109.368736,107.987778,108.614601,109.471199
11387,2023-10-06,A,108.359947,0.262796,1796100.0,108.075928,109.368736,107.987778,109.295273
11883,2023-10-09,A,108.986748,0.578443,1320300.0,108.359947,108.075928,109.368736,108.614601
12379,2023-10-10,A,110.955338,1.806265,2183000.0,108.986748,108.359947,108.075928,107.987778

In [38]:
df['SMA 5'] = df['close'].rolling(window=5).mean()
df['SMA 10'] = df['close'].rolling(window=10).mean()
df['SMA 20'] = df['close'].rolling(window=20).mean()
df['SMA 30'] = df['close'].rolling(window=30).mean()
df['SMA 50'] = df['close'].rolling(window=50).mean()

df.head(100)
#df = fdf[fdf['ticker'] == 'AAPL'].copy()
#df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50
495,2023-09-06,A,115.277092,-0.665382,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635025,-1.424452,1317000.0,115.277092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,2023-09-08,A,111.416275,-1.952523,1789800.0,113.635025,115.277092,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780776,2046900.0,111.416275,113.635025,115.277092,NaN,NaN,NaN,NaN,NaN,NaN
2475,2023-09-12,A,110.233589,-0.282935,2035000.0,110.546364,111.416275,113.635025,NaN,112.221669,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47595,2024-01-23,A,129.145248,-0.686527,854900.0,130.037994,128.733215,127.987617,128.056259,128.319205,128.174983,130.892300,131.264971,126.024056
48091,2024-01-24,A,127.320480,-1.412958,1141900.0,129.145248,130.037994,128.733215,125.691948,128.644911,128.086690,130.423637,131.356364,126.460072
48587,2024-01-25,A,127.418617,0.077079,1120900.0,127.320480,129.145248,130.037994,127.987617,128.531111,127.967985,129.948127,131.393244,126.883750
49083,2024-01-26,A,128.507553,0.854613,1319800.0,127.418617,127.320480,129.145248,128.733215,128.485979,128.096500,129.526575,131.472299,127.348992
49579,2024-01-29,A,130.312668,1.404676,1407200.0,128.507553,127.418617,127.320480,130.037994,128.540913,128.321160,129.197727,131.449924,127.769046

In [39]:
df['volatility 5'] = df['return'].rolling(5).std()
df['volatility 10'] = df['return'].rolling(10).std()
df['volatility 20'] = df['return'].rolling(20).std()
df['volatility 30'] = df['return'].rolling(30).std()
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30
495,2023-09-06,A,115.277092,-0.665382,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635025,-1.424452,1317000.0,115.277092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,2023-09-08,A,111.416275,-1.952523,1789800.0,113.635025,115.277092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780776,2046900.0,111.416275,113.635025,115.277092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2475,2023-09-12,A,110.233589,-0.282935,2035000.0,110.546364,111.416275,113.635025,NaN,112.221669,NaN,NaN,NaN,NaN,0.663216,NaN,NaN,NaN

In [47]:

df['Price change per volume'] = 1000000*(df['return']/df['volume'])
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return,Price change per volume
24779,2023-11-14,A,109.309959,3.861916,2009700.0,105.245468,106.234680,105.519707,108.262009,106.689104,105.685227,104.620628,106.113876,107.759729,2.200766,2.228412,2.166080,1.988021,1.783001,1.921638
25275,2023-11-15,A,111.258957,1.783001,2021400.0,109.309959,105.245468,106.234680,107.135704,107.513754,106.737095,104.864986,106.176883,107.679366,2.160979,2.198596,2.048903,2.000773,0.519361,0.882062
25771,2023-11-16,A,111.836792,0.519361,1728100.0,111.258957,109.309959,105.245468,105.519707,108.777171,107.689065,105.094164,106.302245,107.643401,1.782002,2.194627,2.045427,1.987941,-0.910771,0.300538
26267,2023-11-17,A,110.818214,-0.910771,2700800.0,111.836792,111.258957,109.309959,106.234680,109.693878,108.093552,105.286124,106.384187,107.631440,2.020101,1.887729,2.058802,1.996830,0.733554,-0.337223
26763,2023-11-20,A,111.631126,0.733554,3050000.0,110.818214,111.836792,111.258957,105.245468,110.971010,108.725262,105.513344,106.472333,107.653135,1.772135,1.784792,2.062113,1.998327,8.720810,0.240510

In [48]:
from sklearn.preprocessing import LabelEncoder

df['id'] = LabelEncoder().fit_transform(df['ticker'])
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return,Price change per volume,id
24779,2023-11-14,A,109.309959,3.861916,2009700.0,105.245468,106.234680,105.519707,108.262009,106.689104,...,104.620628,106.113876,107.759729,2.200766,2.228412,2.166080,1.988021,1.783001,1.921638,0
25275,2023-11-15,A,111.258957,1.783001,2021400.0,109.309959,105.245468,106.234680,107.135704,107.513754,...,104.864986,106.176883,107.679366,2.160979,2.198596,2.048903,2.000773,0.519361,0.882062,0
25771,2023-11-16,A,111.836792,0.519361,1728100.0,111.258957,109.309959,105.245468,105.519707,108.777171,...,105.094164,106.302245,107.643401,1.782002,2.194627,2.045427,1.987941,-0.910771,0.300538,0
26267,2023-11-17,A,110.818214,-0.910771,2700800.0,111.836792,111.258957,109.309959,106.234680,109.693878,...,105.286124,106.384187,107.631440,2.020101,1.887729,2.058802,1.996830,0.733554,-0.337223,0
26763,2023-11-20,A,111.631126,0.733554,3050000.0,110.818214,111.836792,111.258957,105.245468,110.971010,...,105.513344,106.472333,107.653135,1.772135,1.784792,2.062113,1.998327,8.720810,0.240510,0

In [51]:
df['mk cap'] = df['close'] * df['volume'] / 100000000
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return,Price change per volume,id,mk cap
24779,2023-11-14,A,109.309959,3.861916,2009700.0,105.245468,106.234680,105.519707,108.262009,106.689104,...,106.113876,107.759729,2.200766,2.228412,2.166080,1.988021,1.783001,1.921638,0,2.196802
25275,2023-11-15,A,111.258957,1.783001,2021400.0,109.309959,105.245468,106.234680,107.135704,107.513754,...,106.176883,107.679366,2.160979,2.198596,2.048903,2.000773,0.519361,0.882062,0,2.248989
25771,2023-11-16,A,111.836792,0.519361,1728100.0,111.258957,109.309959,105.245468,105.519707,108.777171,...,106.302245,107.643401,1.782002,2.194627,2.045427,1.987941,-0.910771,0.300538,0,1.932652
26267,2023-11-17,A,110.818214,-0.910771,2700800.0,111.836792,111.258957,109.309959,106.234680,109.693878,...,106.384187,107.631440,2.020101,1.887729,2.058802,1.996830,0.733554,-0.337223,0,2.992978
26763,2023-11-20,A,111.631126,0.733554,3050000.0,110.818214,111.836792,111.258957,105.245468,110.971010,...,106.472333,107.653135,1.772135,1.784792,2.062113,1.998327,8.720810,0.240510,0,3.404749

In [52]:
df = df.dropna()
#df = df.drop(columns = 'SMA 100')
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return,Price change per volume,id,mk cap
24779,2023-11-14,A,109.309959,3.861916,2009700.0,105.245468,106.234680,105.519707,108.262009,106.689104,...,106.113876,107.759729,2.200766,2.228412,2.166080,1.988021,1.783001,1.921638,0,2.196802
25275,2023-11-15,A,111.258957,1.783001,2021400.0,109.309959,105.245468,106.234680,107.135704,107.513754,...,106.176883,107.679366,2.160979,2.198596,2.048903,2.000773,0.519361,0.882062,0,2.248989
25771,2023-11-16,A,111.836792,0.519361,1728100.0,111.258957,109.309959,105.245468,105.519707,108.777171,...,106.302245,107.643401,1.782002,2.194627,2.045427,1.987941,-0.910771,0.300538,0,1.932652
26267,2023-11-17,A,110.818214,-0.910771,2700800.0,111.836792,111.258957,109.309959,106.234680,109.693878,...,106.384187,107.631440,2.020101,1.887729,2.058802,1.996830,0.733554,-0.337223,0,2.992978
26763,2023-11-20,A,111.631126,0.733554,3050000.0,110.818214,111.836792,111.258957,105.245468,110.971010,...,106.472333,107.653135,1.772135,1.784792,2.062113,1.998327,8.720810,0.240510,0,3.404749

In [41]:
len(df)

362027

In [42]:
df['future return'] = df.groupby('ticker')['return'].shift(-1)
df = df.dropna()
print(len(df))
df.head(len(df))

361524

/tmp/ipykernel_6127/2419459239.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['future return'] = df.groupby('ticker')['return'].shift(-1)

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,future return
24779,2023-11-14,A,109.309959,3.861916,2009700.0,105.245468,106.234680,105.519707,108.262009,106.689104,105.685227,104.620628,106.113876,107.759729,2.200766,2.228412,2.166080,1.988021,1.783001
25275,2023-11-15,A,111.258957,1.783001,2021400.0,109.309959,105.245468,106.234680,107.135704,107.513754,106.737095,104.864986,106.176883,107.679366,2.160979,2.198596,2.048903,2.000773,0.519361
25771,2023-11-16,A,111.836792,0.519361,1728100.0,111.258957,109.309959,105.245468,105.519707,108.777171,107.689065,105.094164,106.302245,107.643401,1.782002,2.194627,2.045427,1.987941,-0.910771
26267,2023-11-17,A,110.818214,-0.910771,2700800.0,111.836792,111.258957,109.309959,106.234680,109.693878,108.093552,105.286124,106.384187,107.631440,2.020101,1.887729,2.058802,1.996830,0.733554
26763,2023-11-20,A,111.631126,0.733554,3050000.0,110.818214,111.836792,111.258957,105.245468,110.971010,108.725262,105.513344,106.472333,107.653135,1.772135,1.784792,2.062113,1.998327,8.720810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371008,2026-08-20,ZTS,75.019997,-2.164846,3917300.0,76.680000,73.959999,72.970001,75.839996,74.484000,74.464000,75.523500,75.355463,75.731934,2.665302,3.136078,2.572337,2.228188,3.612379
371511,2026-08-21,ZTS,77.730003,3.612379,5049900.0,75.019997,76.680000,73.959999,73.790001,75.272000,74.971000,75.642500,75.445232,75.671989,2.672445,2.616024,2.685540,2.319784,-0.720449
372014,2026-08-24,ZTS,77.169998,-0.720449,4066000.0,77.730003,75.019997,76.680000,72.970001,76.112000,75.205000,75.655000,75.521962,75.598659,2.597205,2.517997,2.654497,2.324259,0.155504
372517,2026-08-25,ZTS,77.290001,0.155504,3475800.0,77.169998,77.730003,75.019997,73.959999,76.778000,75.399000,75.644000,75.646387,75.564076,2.628931,2.515249,2.649318,2.297041,0.297575
373020,2026-08-26,ZTS,77.519997,0.297575,4846800.0,77.290001,77.169998,77.730003,76.680000,76.945999,75.796999,75.623500,75.763252,75.526545,2.126562,2.333353,2.647344,2.295711,-3.224974

In [53]:
features = ['close', 'return', 'Lag 1', 'Lag 2', 'Lag 3', 'Lag 5', 'volatility 5', 'volatility 10', 'volatility 20', 'volatility 30','SMA 10' ,'SMA 20','SMA 30','SMA 50','volume','Price change per volume','id','mk cap']
x = df[features]
y = df['future return']

In [44]:
split_index = int(0.8 * len(df))

x_train, x_test = x.iloc[:split_index], x.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]