In [57]:
from fastai import *
import pandas as pd
from google.colab import userdata
import os
import zipfile
import numpy as np

os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

import kaggle

In [58]:
dataset_id = 'darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily'
path = 'ticker_list'
kaggle.api.dataset_download_cli(dataset_id, path = str(path), unzip=True, force=True)

Dataset URL: https://www.kaggle.com/datasets/darkmatternet/s-and-p-500-stocks-25-years-of-data-updated-daily
License(s): CC0-1.0
Downloading s-and-p-500-stocks-25-years-of-data-updated-daily.zip to ticker_list

100%|██████████| 100M/100M [00:00<00:00, 247MB/s]

In [59]:
!ls {path}

sp500_companies.csv  sp500_stocks.csv

In [60]:
tk = pd.read_csv('ticker_list/sp500_companies.csv')
tk.head()

,symbol,company,sector,sub_industry,headquarters,date_added,founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1989

In [61]:
import numpy as np
tickers = tk['symbol'].tolist()
tickers[0:25]

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE']

In [62]:
len(tickers)

503

In [63]:
tickers[499:503]

['YUM', 'ZBRA', 'ZBH', 'ZTS']

In [64]:
import yfinance as yf
df = yf.download(tickers, period="36mo")
df.head()

/tmp/ipykernel_7317/2136594173.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, period="36mo")
[*********************100%***********************]  503 of 503 completed

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2023-09-05  116.049248  187.168518  131.721817  142.289993  94.771317
2023-09-06  115.277084  180.469116  131.280045  141.770004  95.410141
2023-09-07  113.635033  175.190536  134.255310  143.270004  94.574028
2023-09-08  111.416267  175.802246  134.354477  145.820007  94.630409
2023-09-11  110.546364  176.966492  134.372498  147.330002  96.246246

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2023-09-05  72.135162  308.810669  564.880005  173.242645  71.351158  ...
2023-09-06  72.686684  308.943207  561.940002  173.853409  70.066681  ...
2023-09-07  74.046471  310.742157  560.460022  170.303452  71.034569  ...
2023-09-08  73.466423  308.157318  560.359985  169.358688  71.287849  ...
2023-09-11  74.930809  308.536133  564.500000  169.530441  71.224510  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2023-09-05  4133700  3084700  4170400  18304000  2679700   5987000  1435900
2023-09-06  3342700  1896200  3815400  13325500  1514400  10491600  1710200
2023-09-07  3199500  3111300  3554900  13248500  1807100   9075800  1396800
2023-09-08  3303400  1466700  3627800  14283200  1690800  20691100   728900
2023-09-11  2227200  1068600  5586300  14383600  1617400  10420000   981700

Price
Ticker          ZBH    ZBRA      ZTS
Date
2023-09-05  1645000  417300  1673000
2023-09-06  3625200  327200  1356800
2023-09-07  1816400  498100  1159600
2023-09-08  1104500  435000  1562200
2023-09-11  1285900  358400  1069100

[5 rows x 2515 columns]

In [65]:
df.head()

Price            Close                                                 \
Ticker               A        AAPL        ABBV        ABNB        ABT
Date
2023-09-05  116.049248  187.168518  131.721817  142.289993  94.771317
2023-09-06  115.277084  180.469116  131.280045  141.770004  95.410141
2023-09-07  113.635033  175.190536  134.255310  143.270004  94.574028
2023-09-08  111.416267  175.802246  134.354477  145.820007  94.630409
2023-09-11  110.546364  176.966492  134.372498  147.330002  96.246246

Price                                                                 ...  \
Ticker           ACGL         ACN        ADBE         ADI        ADM  ...
Date                                                                  ...
2023-09-05  72.135162  308.810669  564.880005  173.242645  71.351158  ...
2023-09-06  72.686684  308.943207  561.940002  173.853409  70.066681  ...
2023-09-07  74.046471  310.742157  560.460022  170.303452  71.034569  ...
2023-09-08  73.466423  308.157318  560.359985  169.358688  71.287849  ...
2023-09-11  74.930809  308.536133  564.500000  169.530441  71.224510  ...

Price        Volume                                                          \
Ticker           WY     WYNN      XEL       XOM      XYL       XYZ      YUM
Date
2023-09-05  4133700  3084700  4170400  18304000  2679700   5987000  1435900
2023-09-06  3342700  1896200  3815400  13325500  1514400  10491600  1710200
2023-09-07  3199500  3111300  3554900  13248500  1807100   9075800  1396800
2023-09-08  3303400  1466700  3627800  14283200  1690800  20691100   728900
2023-09-11  2227200  1068600  5586300  14383600  1617400  10420000   981700

Price
Ticker          ZBH    ZBRA      ZTS
Date
2023-09-05  1645000  417300  1673000
2023-09-06  3625200  327200  1356800
2023-09-07  1816400  498100  1159600
2023-09-08  1104500  435000  1562200
2023-09-11  1285900  358400  1069100

[5 rows x 2515 columns]

In [66]:
closes = df["Close"]
returns = closes.pct_change() *100

volumes = df['Volume']

cs = closes.stack().rename("Close")
rs = returns.stack().rename("Returns")
vs = volumes.stack().rename("Volume")
fdf = pd.concat([cs,rs,vs], axis = 1).reset_index()

fdf.columns = ['date', 'ticker', 'close', 'return', 'volume']
fdf = fdf.dropna(subset=['return'])

fdf.head(25)

/tmp/ipykernel_7317/4234654860.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = closes.pct_change() *100

          date ticker       close    return      volume
495 2023-09-06      A  115.277084 -0.665376   1668900.0
496 2023-09-06   AAPL  180.469116 -3.579342  81755800.0
497 2023-09-06   ABBV  131.280045 -0.335383   5304300.0
498 2023-09-06   ABNB  141.770004 -0.365443   7114400.0
499 2023-09-06    ABT   95.410141  0.674069   5094400.0
500 2023-09-06   ACGL   72.686684  0.764567    922800.0
501 2023-09-06    ACN  308.943207  0.042919   1247900.0
502 2023-09-06   ADBE  561.940002 -0.520465   2299900.0
503 2023-09-06    ADI  173.853409  0.352548   3382500.0
504 2023-09-06    ADM   70.066681 -1.800219   3563900.0
505 2023-09-06    ADP  233.969437 -0.711885   1311000.0
506 2023-09-06   ADSK  222.199997  1.248515   1709700.0
507 2023-09-06    AEE   70.799110  0.504647   1205900.0
508 2023-09-06    AEP   68.546913  0.499984   2752300.0
509 2023-09-06    AES   15.046948 -0.057377  10449000.0
510 2023-09-06    AFL   69.647827  0.040427   2240900.0
511 2023-09-06    AIG   55.399822  1.006818   2787400.0
512 2023-09-06    AIZ  131.791885 -0.245808    336100.0
513 2023-09-06    AJG  221.853973  0.414444    519100.0
514 2023-09-06   AKAM  103.800003 -0.717360   1197800.0
515 2023-09-06    ALB  181.296814 -5.463157   2544100.0
516 2023-09-06   ALGN  369.700012  0.290266    618500.0
517 2023-09-06    ALL  101.528931  0.662176   1360300.0
518 2023-09-06   ALLE  104.403679 -2.402362   1301100.0
519 2023-09-06   AMAT  149.630814 -0.279934   3109600.0

fdf.sort_values(by=['ticker', 'date'], inplace=True)
fdf.head(25)

In [67]:
fdf.sort_values(['ticker', 'date'], inplace=True)
fdf.head(25)

            date ticker       close    return     volume
495   2023-09-06      A  115.277084 -0.665376  1668900.0
990   2023-09-07      A  113.635033 -1.424439  1317000.0
1485  2023-09-08      A  111.416267 -1.952536  1789800.0
1980  2023-09-11      A  110.546364 -0.780769  2046900.0
2475  2023-09-12      A  110.233597 -0.282928  2035000.0
2970  2023-09-13      A  110.868919  0.576342  2520500.0
3465  2023-09-14      A  112.286179  1.278320  1815800.0
3960  2023-09-15      A  113.292923  0.896588  6889600.0
4455  2023-09-18      A  110.145615 -2.778027  1818000.0
4950  2023-09-19      A  109.774208 -0.337196  2222400.0
5445  2023-09-20      A  109.930595  0.142463  1744900.0
5940  2023-09-21      A  107.252472 -2.436195  1327900.0
6435  2023-09-22      A  108.894539  1.531029  2050500.0
6930  2023-09-25      A  109.412567  0.475716   987400.0
7425  2023-09-26      A  108.229881 -1.080942  1399800.0
7920  2023-09-27      A  108.005074 -0.207713  2268300.0
8415  2023-09-28      A  109.471207  1.357467  1959900.0
8910  2023-09-29      A  109.295265 -0.160719  1830100.0
9405  2023-10-02      A  108.614594 -0.622782  1569000.0
9900  2023-10-03      A  107.987778 -0.577101  1543400.0
10395 2023-10-04      A  109.368729  1.278803  1541700.0
10891 2023-10-05      A  108.075920 -1.182064  1295700.0
11387 2023-10-06      A  108.359962  0.262817  1796100.0
11883 2023-10-09      A  108.986755  0.578436  1320300.0
12379 2023-10-10      A  110.955330  1.806251  2183000.0

In [68]:
df=fdf

In [69]:
len(df)

375035

In [70]:
df['Lag 1'] = df['close'].shift(1)
df['Lag 2'] = df['close'].shift(2)
df['Lag 3'] = df['close'].shift(3)
df['Lag 5'] = df['close'].shift(5)
df.head(200)

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN
...,...,...,...,...,...,...,...,...,...
97365,2024-06-14,A,127.596130,-0.551430,2163300.0,128.303635,130.848663,129.816895,130.671783
97864,2024-06-17,A,129.541748,1.524825,2090500.0,127.596130,128.303635,130.848663,130.720901
98363,2024-06-18,A,132.558456,2.328754,3453000.0,129.541748,127.596130,128.303635,129.816895
98862,2024-06-20,A,130.426132,-1.608592,2887400.0,132.558456,129.541748,127.596130,130.848663
99361,2024-06-21,A,130.937088,0.391759,4449700.0,130.426132,132.558456,129.541748,128.303635

In [71]:
df['Lag 1'] = df.groupby('ticker')['close'].shift(1)
df['Lag 2'] = df.groupby('ticker')['close'].shift(2)
df['Lag 3'] = df.groupby('ticker')['close'].shift(3)
df['Lag 5'] = df.groupby('ticker')['close'].shift(5)
df.head(25)

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN
2970,2023-09-13,A,110.868919,0.576342,2520500.0,110.233597,110.546364,111.416267,115.277084
3465,2023-09-14,A,112.286179,1.278320,1815800.0,110.868919,110.233597,110.546364,113.635033
3960,2023-09-15,A,113.292923,0.896588,6889600.0,112.286179,110.868919,110.233597,111.416267
4455,2023-09-18,A,110.145615,-2.778027,1818000.0,113.292923,112.286179,110.868919,110.546364
4950,2023-09-19,A,109.774208,-0.337196,2222400.0,110.145615,113.292923,112.286179,110.233597
5445,2023-09-20,A,109.930595,0.142463,1744900.0,109.774208,110.145615,113.292923,110.868919
5940,2023-09-21,A,107.252472,-2.436195,1327900.0,109.930595,109.774208,110.145615,112.286179
6435,2023-09-22,A,108.894539,1.531029,2050500.0,107.252472,109.930595,109.774208,113.292923
6930,2023-09-25,A,109.412567,0.475716,987400.0,108.894539,107.252472,109.930595,110.145615
7425,2023-09-26,A,108.229881,-1.080942,1399800.0,109.412567,108.894539,107.252472,109.774208
7920,2023-09-27,A,108.005074,-0.207713,2268300.0,108.229881,109.412567,108.894539,109.930595
8415,2023-09-28,A,109.471207,1.357467,1959900.0,108.005074,108.229881,109.412567,107.252472
8910,2023-09-29,A,109.295265,-0.160719,1830100.0,109.471207,108.005074,108.229881,108.894539
9405,2023-10-02,A,108.614594,-0.622782,1569000.0,109.295265,109.471207,108.005074,109.412567
9900,2023-10-03,A,107.987778,-0.577101,1543400.0,108.614594,109.295265,109.471207,108.229881
10395,2023-10-04,A,109.368729,1.278803,1541700.0,107.987778,108.614594,109.295265,108.005074
10891,2023-10-05,A,108.075920,-1.182064,1295700.0,109.368729,107.987778,108.614594,109.471207
11387,2023-10-06,A,108.359962,0.262817,1796100.0,108.075920,109.368729,107.987778,109.295265
11883,2023-10-09,A,108.986755,0.578436,1320300.0,108.359962,108.075920,109.368729,108.614594
12379,2023-10-10,A,110.955330,1.806251,2183000.0,108.986755,108.359962,108.075920,107.987778

In [72]:
df['SMA 5'] = df['close'].rolling(window=5).mean()
df['SMA 10'] = df['close'].rolling(window=10).mean()
df['SMA 20'] = df['close'].rolling(window=20).mean()
df['SMA 30'] = df['close'].rolling(window=30).mean()
df['SMA 50'] = df['close'].rolling(window=50).mean()

df.head(100)
#df = fdf[fdf['ticker'] == 'AAPL'].copy()
#df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN,112.221669,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47595,2024-01-23,A,129.145264,-0.686527,854900.0,130.038010,128.733215,127.987602,128.056290,128.319206,128.174988,130.892307,131.264972,126.024056
48091,2024-01-24,A,127.320518,-1.412940,1141900.0,129.145264,130.038010,128.733215,125.691940,128.644922,128.086698,130.423643,131.356367,126.460072
48587,2024-01-25,A,127.418602,0.077037,1120900.0,127.320518,129.145264,130.038010,127.987602,128.531122,127.967990,129.948133,131.393246,126.883751
49083,2024-01-26,A,128.507568,0.854637,1319800.0,127.418602,127.320518,129.145264,128.733215,128.485992,128.096510,129.526581,131.472302,127.348993
49579,2024-01-29,A,130.312698,1.404688,1407200.0,128.507568,127.418602,127.320518,130.038010,128.540930,128.321171,129.197733,131.449929,127.769047

In [73]:
df['volatility 5'] = df['return'].rolling(5).std()
df['volatility 10'] = df['return'].rolling(10).std()
df['volatility 20'] = df['return'].rolling(20).std()
df['volatility 30'] = df['return'].rolling(30).std()
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN,112.221669,NaN,NaN,NaN,NaN,0.663222,NaN,NaN,NaN

In [74]:

df['Price change per volume'] = 1000000*(df['return']/df['volume'])
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.398691
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.081579
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.090924
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.381440
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN,112.221669,NaN,NaN,NaN,NaN,0.663222,NaN,NaN,NaN,-0.139031

In [75]:
from sklearn.preprocessing import LabelEncoder

df['id'] = LabelEncoder().fit_transform(df['ticker'])
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,SMA 10,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.398691,0
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.081579,0
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.090924,0
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.381440,0
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN,112.221669,NaN,NaN,NaN,NaN,0.663222,NaN,NaN,NaN,-0.139031,0

In [76]:
df['mk cap'] = df['close'] * df['volume'] / 100000000
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id,mk cap
495,2023-09-06,A,115.277084,-0.665376,1668900.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.398691,0,1.923859
990,2023-09-07,A,113.635033,-1.424439,1317000.0,115.277084,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.081579,0,1.496573
1485,2023-09-08,A,111.416267,-1.952536,1789800.0,113.635033,115.277084,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.090924,0,1.994128
1980,2023-09-11,A,110.546364,-0.780769,2046900.0,111.416267,113.635033,115.277084,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.381440,0,2.262774
2475,2023-09-12,A,110.233597,-0.282928,2035000.0,110.546364,111.416267,113.635033,NaN,112.221669,...,NaN,NaN,NaN,0.663222,NaN,NaN,NaN,-0.139031,0,2.243254

In [77]:
df = df.dropna()
#df = df.drop(columns = 'SMA 100')
df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 20,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id,mk cap
24779,2023-11-14,A,109.309975,3.861930,2009700.0,105.245468,106.234665,105.519722,108.262009,106.689107,...,104.620627,106.113875,107.759728,2.200766,2.228405,2.166075,1.988015,1.921645,0,2.196803
25275,2023-11-15,A,111.258957,1.782987,2021400.0,109.309975,105.245468,106.234665,107.135704,107.513757,...,104.864985,106.176883,107.679366,2.160976,2.198589,2.048898,2.000766,0.882055,0,2.248989
25771,2023-11-16,A,111.836800,0.519367,1728100.0,111.258957,109.309975,105.245468,105.519722,108.777173,...,105.094164,106.302245,107.643401,1.782003,2.194620,2.045423,1.987935,0.300542,0,1.932652
26267,2023-11-17,A,110.818222,-0.910771,2700800.0,111.836800,111.258957,109.309975,106.234665,109.693884,...,105.286125,106.384187,107.631440,2.020102,1.887723,2.058797,1.996823,-0.337223,0,2.992979
26763,2023-11-20,A,111.631119,0.733541,3050000.0,110.818222,111.836800,111.258957,105.245468,110.971014,...,105.513344,106.472333,107.653135,1.772139,1.784788,2.062109,1.998321,0.240505,0,3.404749

In [78]:
len(df)

349863

In [79]:
df['future return'] = df.groupby('ticker')['return'].shift(-1)
df = df.dropna()
print(len(df))
df.head(len(df))

/tmp/ipykernel_7317/2419459239.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['future return'] = df.groupby('ticker')['return'].shift(-1)

349360

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id,mk cap,future return
24779,2023-11-14,A,109.309975,3.861930,2009700.0,105.245468,106.234665,105.519722,108.262009,106.689107,...,106.113875,107.759728,2.200766,2.228405,2.166075,1.988015,1.921645,0,2.196803,1.782987
25275,2023-11-15,A,111.258957,1.782987,2021400.0,109.309975,105.245468,106.234665,107.135704,107.513757,...,106.176883,107.679366,2.160976,2.198589,2.048898,2.000766,0.882055,0,2.248989,0.519367
25771,2023-11-16,A,111.836800,0.519367,1728100.0,111.258957,109.309975,105.245468,105.519722,108.777173,...,106.302245,107.643401,1.782003,2.194620,2.045423,1.987935,0.300542,0,1.932652,-0.910771
26267,2023-11-17,A,110.818222,-0.910771,2700800.0,111.836800,111.258957,109.309975,106.234665,109.693884,...,106.384187,107.631440,2.020102,1.887723,2.058797,1.996823,-0.337223,0,2.992979,0.733541
26763,2023-11-20,A,111.631119,0.733541,3050000.0,110.818222,111.836800,111.258957,105.245468,110.971014,...,106.472333,107.653135,1.772139,1.784788,2.062109,1.998321,0.240505,0,3.404749,8.720831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372517,2026-08-25,ZTS,77.290001,0.155504,3475800.0,77.169998,77.730003,75.019997,73.959999,76.778000,...,75.646387,75.564076,2.628931,2.515249,2.649318,2.297041,0.044739,502,2.686446,0.297575
373020,2026-08-26,ZTS,77.519997,0.297575,4846800.0,77.290001,77.169998,77.730003,76.680000,76.945999,...,75.763252,75.526545,2.126562,2.333353,2.647344,2.295711,0.061396,502,3.757239,-3.224974
373523,2026-08-27,ZTS,75.019997,-3.224974,3972600.0,77.519997,77.290001,77.169998,75.019997,76.945999,...,75.718000,75.451329,2.453500,2.417698,2.691082,2.304255,-0.811804,502,2.980244,3.092508
374026,2026-08-28,ZTS,77.339996,3.092508,4844300.0,75.019997,77.519997,77.290001,77.730003,76.867998,...,75.761666,75.463625,2.267370,2.414346,2.756842,2.371936,0.638381,502,3.746581,-0.310315
374529,2026-08-31,ZTS,77.099998,-0.310315,5798800.0,77.339996,75.019997,77.519997,77.169998,76.853998,...,75.791666,75.442323,2.245722,2.367900,2.757231,2.372857,-0.053514,502,4.470875,0.194555

In [80]:
df['close'] = df['close'] / 100
df['close'] = 1 / (1 + np.exp(-df['close']))
df['volume'] = df['volume'] / 10000000
df['volume'] = 1 / (1 + np.exp(-df['volume']))


df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id,mk cap,future return
24779,2023-11-14,A,0.748965,3.861930,0.550074,105.245468,106.234665,105.519722,108.262009,106.689107,...,106.113875,107.759728,2.200766,2.228405,2.166075,1.988015,1.921645,0,2.196803,1.782987
25275,2023-11-15,A,0.752612,1.782987,0.550364,109.309975,105.245468,106.234665,107.135704,107.513757,...,106.176883,107.679366,2.160976,2.198589,2.048898,2.000766,0.882055,0,2.248989,0.519367
25771,2023-11-16,A,0.753686,0.519367,0.543095,111.258957,109.309975,105.245468,105.519722,108.777173,...,106.302245,107.643401,1.782003,2.194620,2.045423,1.987935,0.300542,0,1.932652,-0.910771
26267,2023-11-17,A,0.751790,-0.910771,0.567113,111.836800,111.258957,109.309975,106.234665,109.693884,...,106.384187,107.631440,2.020102,1.887723,2.058797,1.996823,-0.337223,0,2.992979,0.733541
26763,2023-11-20,A,0.753304,0.733541,0.575664,110.818222,111.836800,111.258957,105.245468,110.971014,...,106.472333,107.653135,1.772139,1.784788,2.062109,1.998321,0.240505,0,3.404749,8.720831

In [81]:
df['Lag 1'] = df['Lag 1'] / 100
df['Lag 2'] = df['Lag 2'] / 100
df['Lag 3'] = df['Lag 3'] / 100
df['Lag 5'] = df['Lag 5'] / 100
df['SMA 5'] = df['SMA 5'] / 100
df['SMA 10'] = df['SMA 10'] / 100
df['SMA 20'] = df['SMA 20'] / 100
df['SMA 30'] = df['SMA 30'] / 100
df['SMA 50'] = df['SMA 50'] / 100

def sigmoid (number):
  return 1 / (1 + np.exp(-number))

funcs = [
  'Lag 1',
  'Lag 2',
  'Lag 3',
  'Lag 5',
  'SMA 5',
  'SMA 10',
  'SMA 20',
  'SMA 30',
  'SMA 50',
]
for func in funcs:
  df[func] = df[func].apply(sigmoid)

df.head()

,date,ticker,close,return,volume,Lag 1,Lag 2,Lag 3,Lag 5,SMA 5,...,SMA 30,SMA 50,volatility 5,volatility 10,volatility 20,volatility 30,Price change per volume,id,mk cap,future return
24779,2023-11-14,A,0.748965,3.861930,0.550074,0.741246,0.743139,0.741772,0.746989,0.744005,...,0.742908,0.746039,2.200766,2.228405,2.166075,1.988015,1.921645,0,2.196803,1.782987
25275,2023-11-15,A,0.752612,1.782987,0.550364,0.748965,0.741246,0.743139,0.744855,0.745573,...,0.743028,0.745887,2.160976,2.198589,2.048898,2.000766,0.882055,0,2.248989,0.519367
25771,2023-11-16,A,0.753686,0.519367,0.543095,0.752612,0.748965,0.741246,0.741772,0.747962,...,0.743268,0.745819,1.782003,2.194620,2.045423,1.987935,0.300542,0,1.932652,-0.910771
26267,2023-11-17,A,0.751790,-0.910771,0.567113,0.753686,0.752612,0.748965,0.743139,0.749686,...,0.743424,0.745796,2.020102,1.887723,2.058797,1.996823,-0.337223,0,2.992979,0.733541
26763,2023-11-20,A,0.753304,0.733541,0.575664,0.751790,0.753686,0.752612,0.741246,0.752075,...,0.743592,0.745837,1.772139,1.784788,2.062109,1.998321,0.240505,0,3.404749,8.720831

In [82]:
cont_variables = ['close', 'return', 'Lag 1', 'Lag 2', 'Lag 3', 'Lag 5', 'volatility 5', 'volatility 10', 'volatility 20', 'volatility 30','SMA 10' ,'SMA 20','SMA 30','SMA 50','volume','Price change per volume','mk cap']

features = ['close', 'return', 'Lag 1', 'Lag 2', 'Lag 3', 'Lag 5', 'volatility 5', 'volatility 10', 'volatility 20', 'volatility 30','SMA 10' ,'SMA 20','SMA 30','SMA 50','volume','Price change per volume','id','mk cap']
x = df[features]
y = df['future return']

In [83]:
split_index = int(0.8 * len(df))

x_train, x_test = x.iloc[:split_index], x.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

In [84]:
from fastai.tabular.all import *
from sklearn.metrics import mean_squared_error

dls = TabularDataLoaders.from_df(df,y_names='future return',cont_names = cont_variables, cat_names = 'id',
                                 procs=[Categorify, FillMissing, Normalize],
                                 splits=RandomSplitter(valid_pct=0.2)(df))

learn = tabular_learner(dls, layers = [500,400,300,200,100],metrics=mse,)
learn.fit_one_cycle(10)

x_test = dls.test_dl(x_test)

preds,_ = learn.get_preds(dl=x_test)
error =mean_squared_error(y_test, preds)
error

<div><table class="fastprogress"><thead><tr><th>epoch</th><th>train_loss</th><th>valid_loss</th><th>mse</th><th>time</th></tr></thead><tbody><tr><td>0</td><td>4.878544</td><td>8.025501</td><td>8.025501</td><td>01:29</td></tr><tr><td>1</td><td>4.717642</td><td>15.503977</td><td>15.503977</td><td>01:25</td></tr><tr><td>2</td><td>4.791825</td><td>5.154816</td><td>5.154816</td><td>01:24</td></tr><tr><td>3</td><td>5.083115</td><td>5.175201</td><td>5.175201</td><td>01:24</td></tr><tr><td>4</td><td>4.733626</td><td>5.140938</td><td>5.140938</td><td>01:25</td></tr><tr><td>5</td><td>5.444042</td><td>5.134708</td><td>5.134708</td><td>01:26</td></tr><tr><td>6</td><td>4.493763</td><td>5.139803</td><td>5.139803</td><td>01:25</td></tr><tr><td>7</td><td>4.827177</td><td>5.303504</td><td>5.303504</td><td>01:28</td></tr><tr><td>8</td><td>4.694351</td><td>5.131505</td><td>5.131505</td><td>01:26</td></tr><tr><td>9</td><td>4.431876</td><td>5.134945</td><td>5.134945</td><td>01:27</td></tr></tbody></table></div>

5.047125906831015